### ISSUE TITLE
direnv not working in devcontainer

### ISSUE THREAD

**Issue by giannoug** [onedr0p/flux-cluster-template#1106]
This is (probably) the last issue with dev containers, but I have no idea how to fix.

After opening a dev container, running any command that requires the venv to be activated (i.e. have packages in PATH) fails. For example:
```
vscode ➜ /workspaces/flux-cluster-template (main) $ task configure
Any conflicting config in the root kubernetes and ansible directories will be overwritten... continue? [y/N]
y
task: [configure] ansible-playbook configure.yaml
"ansible-playbook": executable file not found in $PATH
task: Failed to run task "configure": exit status 127
```

How is that handled in the project? Is the venv activated in task files? Is the path manually set? For the time being I just `source .venv/bin/activate` before running any task.

**Comment by onedr0p** [comment]
`task deps` should set up the venv and then the taskfiles should have that in the env section that updates PATH with the venv bin path.

**Comment by giannoug** [comment]
This didn't work when I had it setup in Linux too, so it's not a dev container issue. From brew I understand you are on a Mac. I also found this: https://github.com/go-task/task/issues/482

**Comment by onedr0p** [comment]
Funny how I was already subscribed to that issue 😂. Yeah I don't have a bunch of systems to test on so many with mac it _just works_?

**Comment by onedr0p** [comment]
Actually come to think of it, maybe it is direnv setting that all up and it's not really needed in the taskfile?

**Comment by giannoug** [comment]
You mean we can set it in `.envrc` instead of  `Taskfile.yaml`? Not sure, haven't used neither of them. I also discovered that direnv is not installed in dev container, so I might want to check that first.

**Comment by onedr0p** [comment]
Installing direnv might be easy, the harder part might be getting it hooked into the zsh shell

https://direnv.net/docs/hook.html#zsh

**Comment by giannoug** [comment]
Fortunately it's done automatically [according to docs](https://github.com/devcontainers-community/features-direnv?tab=readme-ov-file#direnv-dev-container-feature):
```
Installs direnv and sets up hooks
```

Problem is, the feature I linked above doesn't seem to work in the project 🤔 It breaks upon dev container creation

**Comment by onedr0p** [comment]
maybe we need to remove the `task deps` from the post install?

**Comment by giannoug** [comment]
Whoops, sorry I edited my comment before your reply. I got it working, I'm now checking the PATH issue!

**Comment by giannoug** [comment]
Yeah, that did it.

```
vscode ➜ /workspaces/flux-cluster-template (main) $ echo $PATH                      
/workspaces/flux-cluster-template/.venv/bin:/vscode/vscode-server/bin/linux-x64/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/bin/remote-cli:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/vscode/.local/bin
```

Problem is, automatic hooking didn't work even though [it's supposed to](https://github.com/devcontainers-community/features-direnv/blob/main/install.sh#L12). I'll open an issue on the feature repo. In the meantime I think we can work on cleaning up Taskfile `env` declarations and moving them to envrc. It seems that there are variables defined twice (e.g. `SOPS_AGE_KEY_FILE`) 🤔 

Of course, `task configure` now runs:
```
vscode ➜ /workspaces/flux-cluster-template (main) $ task configure
Any conflicting config in the root kubernetes and ansible directories will be overwritten... continue? [y/N]
y
task: [configure] ansible-playbook configure.yaml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Cluster Installation] ****************************************************************************************************************************************************************************
^Ctask: Signal received: "interrupt"
 [ERROR]: User interrupted execution
task: Failed to run task "configure": exit status 99
```

**Comment by onedr0p** [comment]
I wonder do you think if we used bash instead of zsh direnv would work?

**Comment by onedr0p** [comment]
I have fixed this in the latest devcontainer, @giannoug I will close this issue. Will reopen if there's more issues.

**Comment by jasondamour** [comment]
@onedr0p I'm still facing the same issue on the latest feature version

**Comment by onedr0p** [comment]
...This project doesn't use ansible anymore.

**Comment by jasondamour** [comment]
If you do, please link it here
